### PR TITLE
Fixed Forecast Temperature when using OpenWeatherMap

### LINKED ISSUE #16: Weather Forecast Doesn’t Load
While current weather populated perfectly, I can’t seem to get the weather forecast to appear. It just shows “...” instead of other information. Settings are to use OpenWeather and GPS location for weather information.

### PR DESCRIPTION
**Pull request by shawnline**
Prior to this code change, forecast temperatures using OpenWeatherMap failed to load correctly. It does now.

### CODE REVIEW

**Comment by plarus** [comment]
Hello Shawnjoseph2001

Thanks for this pull request.
I haven't used my pebble watch for a while.
So I don't work too much on this project anymore and I'm not sure to make a new version...

Pierre

**Comment by shawnline** [comment]
Hello! Can I have your permission to update the version of this app on the Rebble store with this fixed version? One of the maintainers on the store has allowed me to do so as long as I get your permission. They can do it for you without any work from you. You can review my code changes if you want, very little is changed between the versions except for the forecast fix. Thank you!

**Review by KyNorthstar — CHANGES_REQUESTED** [review]
Don't forget to remove `.DS_Store` from this PR 😁

**Comment by KyNorthstar** [comment]
Thanks, @Shawnjoseph2001! Just don't forget about Git's weirdness where it doesn't remove files ignored after they were committed; they still have to be manually removed.

**Comment by plarus** [comment]
Hello @Shawnjoseph2001!

You will provide the app with your own openweathermap private key?
How do I give you this authorization?

**Comment by shawnline** [comment]
Yeah, I have my own OWM key. Just respond to this thread saying you’d be OK with it, and I’ll show it to the Rebble admins. https://prnt.sc/xxgwxl

Shawn

--

/// ||  ||   /\ \\   /\   //|\ ||
\\\ ||||||  //\\ \\ //\\ // |\\||
/// ||  || //  \\ \//  \\/  ||\\|
Shawn Joseph

**Comment by plarus** [comment]
Ok, I give you the permission to update the version of this app on the
Rebble store with this fixed version

Pierre

Le dim. 31 janv. 2021 à 18:47, Shawn Joseph <notifications@github.com> a
écrit :

> Yeah, I have my own OWM key. Just respond to this thread saying you’d be
> OK with it, and I’ll show it to the Rebble admins. https://prnt.sc/xxgwxl
>
> Shawn
>
> --
>
> /// ||  ||   /\ \\   /\   //|\ ||
> \\\ ||||||  //\\ \\ //\\ // |\\||
> /// ||  || //  \\ \//  \\/  ||\\|
> Shawn Joseph

**Pull request closed without merging**
